### ISSUE TITLE
TypeError: Cannot convert undefined or null to object in cache.ts { set }

### ISSUE THREAD

**Issue by andreas-karlsson** [octokit/auth-app.js#173]
I'm using this lib with an older version of GHE. In some cases the post to `/app/installations/:installation_id/access_tokens` returns a payload without the permissions object. This in turn causes the set function in cache.ts to blow up on the following line: https://github.com/octokit/auth-app.js/blob/fb13fa22f6beff408b902dd1d1f00996d2b462df/src/cache.ts#L74

**Comment by gr2m** [comment]
Which GHE version? There is a note about GHE 2.18 in the README for exactly that problem

<img width="887" alt="image" src="https://user-images.githubusercontent.com/39992/93101586-4fd66c80-f65f-11ea-8ecd-530fcc27d7e2.png">

Note 2.18 is no longer maintained as of this month

**Comment by andreas-karlsson** [comment]
Right! Thanks. Didn't see that... still, this can't be completely circumvented by the user due to https://github.com/octokit/auth-app.js/blob/fb13fa22f6beff408b902dd1d1f00996d2b462df/src/hook.ts#L36

Would you accept a PR that just adds an empty permissions object in that call site?

**Comment by gr2m** [comment]
I'm not sure what you mean? Could you explain? If it's easier to discuss it directly in code then feel free to start a PR and we can take the discussion there

**Comment by gr2m** [comment]
closing as par https://github.com/octokit/auth-app.js/pull/175#discussion_r488135110
