### ISSUE TITLE
Add a new `log` option to `createAppAuth(options)`, then replace `console.warn` with `state.log.warn`

### ISSUE THREAD

**Issue by gr2m** [octokit/auth-app.js#176]
We are trying to avoid any direct calls to `console`, so that consumers of the Octokit libraries can use their own logging tool. The way we do that is a `log` option that is compatible with the global `console` object. It should at least set `{ debug, info, warn, error }`. By default, `{ debug, info }` are no-ops, the other two default to `console.warn` and `console.error` respectively. Compare https://github.com/octokit/core.js#logging / https://github.com/octokit/core.js/blob/37437bcf632ce32ba25663e575de96a844b802b2/src/index.ts#L111-L119

We introduced `console.warn` statements in #164. These should be replaced with what ever is passed as `options.log.warn` to the `createAppAuth` method.

I'd happily accept a pull request and will provide guidance if you are interested in contributing. The pull request should add a test (or adjust an existing one), it should implement the feature, and add the new option to the documentation in `README.md`

**Comment by romanbalayan** [comment]
Hi @gr2m, 
I opened a PR for this. I'm still quite unsure how to go about testing the log methods - debug, info, and error. Currently they are not covered on the test cases.

**Comment by gr2m** [comment]
thanks @romanbalayan, great work! resolved via https://github.com/octokit/auth-app.js/pull/190
