### ISSUE TITLE
'type: "auth"' not working

### ISSUE THREAD

**Issue by BrunoBlanes** [octokit/auth-app.js#192]
I have an Octokit instance setup as shown below:

```js
import { Octokit as HttpClient } from '@octokit/core';
import { createAppAuth } from '@octokit/auth-app';
import { Azure } from './Azure';

export class Octokit {
    public static Client: HttpClient;

    public static async SetClientAsync(): Promise<void> {
	this.Client = new HttpClient({
		authStrategy: createAppAuth,
		auth: {
			id: 72569,
			type: 'app',
			privateKey: await Azure.GetPrivateKeyAsync()
		},
		previews: [
			'machine-man'
		],
		log: {
			debug: console.debug,
			info: console.info,
			warn: console.warn,
			error: console.error
		},
		userAgent: 'Creeper-Bot',
		timeZone: 'America/Sao_Paulo'
	});
    }
}
```

And I get the following error when trying to make a request:
`(node:11452) UnhandledPromiseRejectionWarning: Error: [@octokit/auth-app] installationId option is required for installation authentication.`

```js
let response = await Octokit.Client.request('GET /repos/:owner/:repo/assignees/:assignee', {
	owner: owner,
	repo: repo,
	assignee: assignee
});
```

I've tried following the documentation but there isn't a clear one for app authentication, am I doing something wrong?

**Comment by gr2m** [comment]
For the `GET /repos/:owner/:repo/assignees/:assignee` request, you need to authenticate using an installation access token. You cannot authenticate as the app itself (JWT). In order to create the installation access token, you have to set the `installationId` auth option. Instead of 

```js
		auth: {
			id: 72569,
			type: 'app',
			privateKey: await Azure.GetPrivateKeyAsync()
		},
```

do

```js
		auth: {
			id: 72569,
			privateKey: await Azure.GetPrivateKeyAsync()
			installationId: <installation ID here>
		},
```

I hope to change that in future, because the installation ID can in theory be derived automatically from the `owner` in `GET /repos/:owner/:repo/assignees/:assignee`, but that feature is not yet implemented.

**Comment by BrunoBlanes** [comment]
Thank you for the information, I'll be using installation id from now on.

**Comment by dominguezcelada** [comment]
> I hope to change that in future, because the installation ID can in theory be derived automatically from the `owner` in `GET /repos/:owner/:repo/assignees/:assignee`, but that feature is not yet implemented.

Should we create an issue to implement this enhancement? @gr2m

**Comment by gr2m** [comment]
good call, I'll do it, there is a lot of information I need to lay out, it's all rather complicated
