### ISSUE TITLE
"factory" option for auth method to create a new instance with shared state

### ISSUE THREAD

**Issue by gr2m** [octokit/auth-app.js#197]
When authenticating using an app ID and private key, there is  currently no simple way to derive a new octokit instance which is authenticated as an installation. When implementing a GitHub App which acts on webhook events, we currently have to

1. Create an `octokit` instance with app authentication (`{ id, privateKey }`)
2. For each event, create a new `octokit` instance to which we have to pass the previous app auth options as well as installationId (`{ id, privateKey, installationId }`)
3. Use an external cache instance so that the installation access tokens can be cached across all these instances

In order to get octokit instances for the App and for each installation with a shared cache, something like this is required

```js
const { Octokit } = require("@octokit/core");
const { createAppAuth } = require("@octokit/auth-app");

const CACHE = {};
const globalTokenCache = {
  async get(key) {
    return CACHE[key];
  },
  async set(key, value) {
    CACHE[key] = value;
  },
};

const MyAppOctokit = Octokit.defaults((options = {}) => {
  const defaults = {
    authStrategy: createAppAuth,
    auth: {
      id: process.env.APP_ID,
      privateKey: process.env.APP_PRIVATE_KEY,
      cache: globalTokenCache,
    },
    userAgent: "my-app/1.2.3",
  };

  if (options.auth) {
    defaults.auth.installationId = options.auth.installationId;
  }

  return defaults;
});

const appOctokit = new MyAppOctokit()
const installationOctokit = new MyAppOctokit({ auth: { installationId: 123 } })
```

What would greatly simplified the above code, but achieve the same thing, would be 

```js
const { Octokit } = require("@octokit/core");
const { createAppAuth } = require("@octokit/auth-app");

const MyAppOctokit = Octokit.defaults({
  authStrategy: createAppAuth,
  auth: {
    id: process.env.APP_ID,
    privateKey: process.env.APP_PRIVATE_KEY,
  },
  userAgent: "my-app/1.2.3",
});

const appOctokit = new MyAppOctokit();
const installationOctokit = await appOctokit.auth({ type: "installation-octokit", installationId: 123 })
```

In order for that to be possible, we have to add a new `Octokit` strategy option, and `@octokit/core` will have to set it to `this.constructor` in https://github.com/octokit/core.js/blob/c44da9b6a3ea3edc7882c9f776639215a6f53bca/src/index.ts#L138-L145

**Comment by gr2m** [comment]
# 💡 

> In order for that to be possible, we have to add a new `Octokit` strategy option, and `@octokit/core` will have to set it to `this.constructor` in https://github.com/octokit/core.js/blob/c44da9b6a3ea3edc7882c9f776639215a6f53bca/src/index.ts#L138-L145

instead of an `Octokit` strategy option that would be called internally with `new Octokit({ auth: { [strategy options here] } })`, I figured it makes more sence to call the option `installationAuth` which will be called with just `{ [strategy options here] }`. 

`@octokit/core` can set this option to 

```js
const auth = options.authStrategy(
  Object.assign(
    {
      request: this.request,
      installationAuth: auth => new this.constructor(auth)
    },
    options.auth
  )
);
```

And `@octokit/auth-app` can default to option to `installationAuth: auth => createAppAuth(auth)`, so this would work out-of-the-box:

```js
const appAuth = createAppAuth({
  id: 1,
  privateKey: "-----BEGIN PRIVATE KEY-----\n..."
});

const installationAuth123 = await appAuth({ type: "installation-auth", installationId: 123 })
const installationAuth456 = await appAuth({ type: "installation-auth", installationId: 456 })
```

And all three `*Auth` instances would share the same cache.

**Comment by gr2m** [comment]
Maybe even simpler, instead of introducing an entirely new type `"installation-auth"` or `"installation-octokit"`, we could introduce a new option to the existing `"installation"` and maybe also the `"oauth"` type which would be a function that gets called with all the strategy options plus the `installationId` set in the `auth()` call. Something like this:

```js
const appAuth = createAppAuth({
  id: 1,
  privateKey: "-----BEGIN PRIVATE KEY-----\n..."
});

const installationAuth123 = await appAuth({ type: "installation", installationId: 123, factory: createAppAuth })
```

For `@octokit/core`, no changes would need to be done. But when I have an octokit instance with app authentication and I want an instance with installation authentication, it'd look like this

```js
const appOctokit = new Octokit({ authStrategy: createAppAuth, auth: { id, privateKey })
const installationOctokit = await appOctokit.auth({ installationId, factory: auth => new appOctokit.constructor({ auth }))
```

**Comment by echuber2** [comment]
@gr2m Sorry for the ping. I just wanted to see if the documentation on this might need an update.

**Comment by gr2m** [comment]
Sorry but I cannot help right now, GitHub did not extend my contract:
https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174

Here is how `@octokit/core` passes itself to the configured authentication strategy, hope that helps:
https://github.com/octokit/core.js/blob/master/src/index.ts#L121-L160

**Comment by echuber2** [comment]
@gr2m I see, I'm very sorry to hear that. Thanks for all of your hard work.

It seems like we just need to make sure that the factory function returns a new Octokit specifying both auth and authStrategy for the case of app installation auth. Some of the more implicit attempts threw exceptions that I was not using a string (token?) as auth.
