### ISSUE TITLE
Getting the `installation_id` for an existing installation

### ISSUE THREAD

**Issue by chopfitzroy** [octokit/auth-app.js#233]
I am not sure if this is outside of the scope of this project (or event the Github REST API) but is it possible to get the `installation_id` for an existing install?

The flow I have works while the app is uninstalled, I then prompt the user to install, they are redirected back with the `installation_id` in the query string and I can use that to do an install like so:

```js
// Express middleware...
const setupOctokit = ({ options = {} } = {}) => (request, response, next) => {
    const { githubInstallationId: installationId } = request.body;

    const octokit = new Octokit({
        ...options,
        ...(installationId && {
            authStrategy: createAppAuth,
            auth: {
                installationId,
                privateKey: key,
                id: process.env.API_GH_APP_ID,
            },
        })
    });

    request.octokit = octokit;

    next();
}
```

And then proceed from there, however I do not persist the `installation_id` anywhere (I am trying to do the whole flow DB free). Now the problem is I cannot get the `installation_id` on subsequent visits to the site, if I prompt the user to install again it takes them to the Github page where they can manage the app, ideally I was hoping Github would just redirect already authenticated apps back to the client with the query string a second time.

I believe this [probot issue](https://github.com/probot/probot/issues/1003) may be some what related, and this [Github community post](https://github.community/t/how-to-get-github-app-installation-id-for-a-user/127276/2) is almost exactly the same issue as I am having.

**Comment by gr2m** [comment]
I'm not sure I fully understand. Are you talking about the redirect Setup URL setting that redirects a user to a configured URL of yours after a user installs an app?

<img width="631" alt="image" src="https://user-images.githubusercontent.com/39992/101379607-50029480-3869-11eb-9fb1-24ac1a5cc316.png">

You can retrieve the installation for a user or organization with these requests

1. https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#get-an-organization-installation-for-the-authenticated-app
2. https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#get-a-user-installation-for-the-authenticated-app

Or a repository, if you know both the owner login and the repository name:

https://docs.github.com/en/free-pro-team@latest/rest/reference/apps#get-a-repository-installation-for-the-authenticated-app

If you only know the owner login, and you don't know if it's a user or an organization, I'd send both requests and retrieve the installation id from the request that succeeds. Something like this

```js
const [installation] = [
  await octokit.request('GET /orgs/{org}/installation', { org: login }).catch(error => null)
  await octokit.request('GET /users/{username}/installation', { username: login }).catch(error => null)
].filter(Boolean)

if (!installation) {
  throw new Error(`Installation could not be found for ${login}`)
}

// now you can use installation.id
```

Does that work for you?

By the way you might also be interested in https://github.com/octokit/app.js, which is using the `@octokit/auth-app` authentication strategy internally and provides higher level APIs

**Comment by chopfitzroy** [comment]
Hey @gr2m I think that answers my question perfectly :) 

> I'm not sure I fully understand. Are you talking about the redirect Setup URL setting that redirects a user to a configured URL of yours after a user installs an app?

And yes I was talking about the `?installation_id=XXXX` passed to this URL.

Thank you so much for you response, I was looking for something more like `installation_id` in the request response as opposed to just `id` and completely missed those endpoints.

**Comment by gr2m** [comment]
Glad it works for you! 

If you have a minute, could you elaborate a bit more on your use case? I'm curious how you use the setup redirect and when you need to receive an installation ID for a GitHub user/org. If your code is open source, could you share the URL?

**Comment by chopfitzroy** [comment]
Hey @gr2m yes of course.

Unfortunately the code is not open source (yet... we had some AppEngine credentials end up in the git history and they haven't been removed yet) but I can explain the use case.

Bear in mind this is the first "Github App" I have worked on and I am actually beginning to think I have approached the problem wrong so it might be good to get a sanity check while I am here.

Essentially what we are working on is a "chat style" UI that allows a user to create an issue, the idea is you can define a [JSON schema](https://github.com/team-arcadian/purr-conversation/blob/master/.purr/issue.json) with prompts (i.e "Which browser are you using") and responses (i.e "Chrome", "Firefox", "Edge") or the user can type out a response like a normal chat app.

We then use the questions and answers to populate the issue (you can see examples of test issues created [here](https://github.com/team-arcadian/purr-conversation)) and then create it against the target repo.

Now the original intention was to have the issue created by the actual Github user, however as you can see from the example issues above the issues are being created by the "bot" that is the app, originally I thought this was going to be really easy to change so we powered on ahead as soon as we saw issues being created and it is only now that I am coming back to this and trying to create the issue as the user.

In terms of why we needed to "fetch" the `installation_id` again is that we have no notion of "persisted users", essentially someone accessing the UI can start the conversation before they log in, all they need is the URL i.e `chat.purr.sh?path=issue&repo=purr-conversation&owner=team-arcadian` (not live yet) and they can get going (we fetch the config from the target repo in the query string).

Once they have completed the conversation we redirect them off to the app [install page](https://github.com/apps/purr-chat/installations/new) let them install and then fire them back to the UI where we have cached all their responses, we then use the `installation_id` in the URL to actually create the issue as the "bot" that is the app.

However once the user leaves the UI we lose the `installation_id` and would like to be able to "fetch" it on subsequent visits, we thought that if we sent them back to the install page it would realize the app was already installed and send the user back with the `installation_id`, unfortunately this is not the case.

 Looking at it now I think I might actually need a "Github Oauth App" to do what I want so I am looking to move the API over to this sometime this week, hopefully most of that can be done is this block (form above):

```js
...(installationId && {
            authStrategy: createAppAuth,
            auth: {
                installationId,
                privateKey: key,
                id: process.env.API_GH_APP_ID,
            },
        })
```

If you are more of a visual person I have attached a screenshot of the UI (running locally) as I has finished the conversation and am being prompted to install the "Github App":

![image](https://user-images.githubusercontent.com/2978850/101445837-145dec80-3987-11eb-89f6-070c194dfd50.png)

Let me know if you have any insight.

**Comment by gr2m** [comment]
This is very cool! Love logo and icons are very cute, perfect to soften some angry bug reporters 😆 

So yeah, I think what you want is an OAuth App. GitHub has two types of apps:

1. OAuth Apps
2. GitHub Apps

When you register an OAuth app, you get the client_id and client_secret. There is no installation, you can use it globally right away. The user does the OAuth dance. Your app can initiate it by redirecting to the authorization page on GitHub and setting the required scopes. Once the user grants access to your OAuth App, they get redirected with the one-time code that you can then exchange for an OAuth token to authenticate against GitHub's API. You need a tiny server component to keep the `client_secret`, but the rest could basically be all happening in the front-end. I've created an SDK for OAuth apps which will make it simpler to build: https://github.com/octokit/oauth-app.js

GitHub Apps are the ones that account owners need to install. GitHub Apps also support the OAuth dance, but without scopes. Instead tokens created through the OAuth flow are constrained to repositories the app is installed on and the permission for each installation. I've created an SDK for GitHub Apps, too. However it's fairly new and not very battle tested yet, and it does not take into account that setting scopes has no effect: https://github.com/octokit/app.js

> Once they have completed the conversation we redirect them off to the app [install page](https://github.com/apps/purr-chat/installations/new) let them install and then fire them back to the UI where we have cached all their responses

Keep in mind that I can only install the app on repositories where I have admin access.

**Comment by chopfitzroy** [comment]
Hey @gr2m thank you so much for the kind words! I will be sure to let you know when we go live! And as for the Oauth explanation thank you so much that is EXACLTY what we need, so I will definitely be using `oauth-app.js`  😃

> Keep in mind that I can only install the app on repositories where I have admin access.

We hadn't even thought of this! That would have definitely caught us out!

**Comment by yard2010** [comment]
Don't mean to necro this but it's been almost 3 years, @chopfitzroy is this project live? I'm curious, I would love to try it :)
