### ISSUE TITLE
How does the oauth flow work?

### ISSUE THREAD

**Issue by MoSattler** [octokit/auth-app.js#254]
Hi, 

in order for my GitHub Apps to be installed, I wanted to use the oauth flow. 
In most cases, when you initialise an oauth flow, you get an URL, which you send your users to. 
So I was wondering where does octokit generate the URL, and how do I get it?

**Comment by gr2m** [comment]
You can use https://github.com/octokit/oauth-auth.js for a full SDK to create a server with all necessary APIs for the OAuth flows. See the routes at https://github.com/octokit/oauth-app.js#middlewares

Does that work for you?

There is also https://github.com/octokit/app.js which builds upon https://github.com/octokit/oauth-app.js, but also includes APIs specific to GitHub Apps

**Comment by MoSattler** [comment]
> You can use https://github.com/octokit/oauth-auth.js for a full SDK to create a server with all necessary APIs for the OAuth flows.

Hi @gr2m, thank you for your help! The link does not seem to work for me, I get a 404.

**Comment by gr2m** [comment]
Sorry! I meant https://github.com/octokit/oauth-app.js

**Comment by MoSattler** [comment]
Thank you very much @gr2m, this is very helpful!

**Comment by MoSattler** [comment]
@gr2m just to clarify - the linked repos help me setting up the oauth flow for a GitHub App (not an Oauth App), correct?

**Comment by gr2m** [comment]
> the linked repos help me setting up the oauth flow for a GitHub App (not an Oauth App), correct

- GitHub App SDK: https://github.com/octokit/app.js/
- OAuth App SDK: https://github.com/octokit/oauth-app.js/

> For my use case it is important to act on behalf an organization, not a user.

An organization cannot be an actor to e.g. create a comment. Only user accounts and GitHub Apps can be actors.

What exactly are you trying to build?

**Comment by MoSattler** [comment]
Ok, thank you! I got a bit confused by OAUth apps vs GItHub Apps with OAuth. 
I need to list the members of an organization, on behalf of the organization, hence the need for a GitHub App. 

Thank you very much!
