### ISSUE TITLE
How to create a repository by Github App?

### ISSUE THREAD

**Issue by hcuong** [octokit/auth-app.js#271]
I went through Github API and found some API that we could create a repository like: 

https://docs.github.com/en/rest/reference/repos#create-a-repository-using-a-template
https://docs.github.com/en/rest/reference/repos#create-an-organization-repository
https://docs.github.com/en/rest/reference/repos#create-a-repository-for-the-authenticated-user

But it seems for only OAuth App that we need to scope `repo` permission on that.

I wonder is there a way we can do it on Github App with some kind of app token or installation token? If that we could install the new repository to the App also. It could be amazing fit to my use case.

**Comment by magiclisten** [comment]
I tried with this in my backend but it returned 403:
```
    const installationOctokit = new Octokit({
      authStrategy: createAppAuth,
      auth: {
        appId,
        privateKey,
        installationId,
      },
    });

    const { data } = await installationOctokit.request('POST /orgs/{org}/repos', {
      org,
      name,
    });
```

I just found that there are an App could do it is Stackbit. Don't know how they could get that.

**Comment by gr2m** [comment]
your app/installation needs the `administration` permission in order to create a repository in an organization. And I think you have to install the app on all your repositories.

It does not seem to be possible for user repositories

**Comment by gr2m** [comment]
by the way this is rather a question for GitHub's platform APIs, not Octokit. I'm trying to help the best I can, but the GitHub folks monitoring https://github.community/c/github-ecosystem/37 have better insights and access to the teams working on these features.

**Comment by magiclisten** [comment]
Thanks @gr2m , appreciate it. I'll try more and close the issue.
