### ISSUE TITLE
Repository ID's to be passed into: Installation authentication

### ISSUE THREAD

**Issue by NickLiffen** [octokit/auth-app.js#277]
Hey @gr2m 👋 

Hope you are well 👋 

I am looking to make the most of this module and only pass in the repositories that are required. 

I see in your documentation it says this:

```
repositoryIds | array of string | The `id`s of the repositories that the installation token can access.
```

Can I make sure that the `id` you are talking about in the above statement, is the same as the `databaseID` being returned from this object: [Repository](https://docs.github.com/en/graphql/reference/objects#repository). 

The description of the `databaseID` in the above Graph Object is:

```
Identifies the primary key from the database.
```

I just want to make sure If I pass in these ID's, it's the same as the ID's you expect. 

Hopefully, this issue makes sense 👍 

One of the main reasons I say that is because of the GraphQL  [Repository](https://docs.github.com/en/graphql/reference/objects#repository) object returning `INT` when it comes to `databaseID`, whereas your `id` is a `string` if that makes sense? 👍 

Thanks for your help 👍

**Comment by NickLiffen** [comment]
E.G I would like to run this query:

```
query { 
  organization(login: "orgName"){
    team(slug: "teamName"){
      repositories(first: 100){
        nodes{
          databaseId
        }
        pageInfo{
          endCursor
          hasNextPage
        }
      }
    }
  }
}
```

and take the value from `databaseId` and pass it in to the `repositoryIds` key (obviously turning them into strings). 

There seems to be a lack of information on what makes a `repositoryID`. Not just with this module, but holistically 🤔

**Comment by NickLiffen** [comment]
Hmm, looking [here](https://github.com/octokit/auth-app.js/blob/b7c019d6bbcd7b4ff5b8fece7d28277df9f8789a/src/types.ts#L63) it may be type `number` 🤔

**Comment by NickLiffen** [comment]
I **guess** you are hitting [this](https://docs.github.com/en/rest/reference/apps#create-an-installation-access-token-for-an-app) API Endpoint behind the scenes. 

It looks to support repository names as well:

```
repositories | array of strings | body | List of repository names that the token should have access to
```

It may be worth adding support for passing in repository names, alongside `repositoryID`


So I guess I have two questions now:

- Is `databaseID` the right ID to pass into the `repositoryIds`
- Should `repositoryIds` be an array of numbers, not an array of strings?
- Should raise a PR that adds the capability to pass in an array of strings which are repo nameS? 

Thanks for the help 👍

**Comment by gr2m** [comment]
> So I guess I have three questions now:
> 
>     * Is `databaseID` the right ID to pass into the `repositoryIds`
>     * Should `repositoryIds` be an array of numbers, not an array of strings?
>     * Should raise a PR that adds the capability to pass in an array of strings which are repo nameS?

Yes to all :) Thank you for offering to help!

**Comment by NickLiffen** [comment]
@gr2m amazing 👍 I am going to raise a PR for the bottom two separately if that's okay? I will push the 2nd one for your review tomorrow 👍
