### ISSUE TITLE
Property 'token' does not exist on type 'Authentication'

### ISSUE THREAD

**Issue by jwenz723** [octokit/auth-app.js#282]
I am going to start out by saying I am a total typescript/javascript newb.

I am trying to create a github action using this `@octokit/auth-app` library. I am trying to authenticate to github using an installation ID. For some reason the typing isn't setup properly to allow access of the `token` property of the object that is returned after calling `createAppAuth`. I was able to resolve my issue by adding `: any` to cast to the generic any type so that  properties can be referenced generically. But this doesn't seem like an ideal solution.

## Here is my code that does not succeed:

```typescript
const auth = createAppAuth(createAppAuthOptions);
const installation = await auth({
    installationId: installationId,
    type: "installation",
});
return installation.token;
```

This code results in the following error when compiling:

```bash
TS2339: Property 'token' does not exist on type 'Authentication'.
  Property 'token' does not exist on type 'AppAuthentication'.
```

## Here is my successful code with the `any` type workaround:

```typescript
const auth = createAppAuth(createAppAuthOptions);
const installation:any = await auth({
    installationId: installationId,
    type: "installation",
});
return installation.token;
```

Any suggestions on what I should be doing differently, or is this a bug?

**Comment by gr2m** [comment]
Something is indeed not working correctly, I was able to reproduce the problem with a [TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQQTGHAVxgAs4BfOAMyghDgCIABCZGCAa2BgHoNiSAWgz4GAKDFVCAOzbAI0uMADOAZRhRg0gOYAKAO4ksALjjKNW7QEpE5CcgXm4-UnAC8KdFlz4ipXQhicMHO+ACSACamAIwANEEhYJoAbt4A0mgAnqYM4uRW9o7wLiRo0jDAyFjyih4Y+hjczgIBCcEwmWBoOVrmGAA2-dUKDPEhStJ9g8PSkTEATADMYvkSKuqaOrolZRVVFQoAdOwcZVZAA)

I'm looking into it

**Comment by gr2m** [comment]
> I am trying to create a github action using this `@octokit/auth-app` library

By the way I just did a live coding show where I created a GitHub action that authenticates as an app, it's using the [`App` SDK `octokit`](https://github.com/octokit/octokit.js#app-client), maybe give that a try?

Here is more info on the show and links to the video: https://github.com/gr2m/helpdesk/issues/1

**Comment by gr2m** [comment]
I started a PR with a failing test at https://github.com/octokit/auth-app.js/pull/283. I'll look into fixing this the coming week. I think I'll have to rewrite the types, similar to [how they work in `@octokit/auth-oauth-app`](https://github.com/octokit/auth-oauth-app.js/blob/ce88707cded427fb9fbc380d3e1c9ddc6b0fc13e/src/types.ts#L116-L143). If you feel like hacking on it this weekend, please go ahead, you can start out with the failing test I created and try to fix it
