### ISSUE TITLE
A JSON web token could not be decoded when using installationId

### ISSUE THREAD

**Issue by azgorov** [octokit/auth-app.js#298]
I am not sure where i am making an error but this code when installationId is used. If I change type from installation to app I got a token.

```js
import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";

const privateKey = Buffer.from(
  process.env.OCTOKIT_PRIVATE_KEY_BASE64,
  "base64"
).toString("ascii");
console.log(privateKey);
const appId = parseInt(process.env.OCTOKIT_APP_ID);
const installationId: number = parseInt(process.env.OCTOKIT_APP_INSTALLATION);

const appOctokit = new Octokit({
  authStrategy: createAppAuth,
  auth: {
    appId: appId,
    privateKey: privateKey,
    clientId: process.env.OCTOKIT_CLIENT_ID,
    clientSecret: process.env.OCTOKIT_CLIENT_SECRET,
    installationId: installationId,
  },
});
```

**Comment by gr2m** [comment]
can you log out `installationId`? Maybe it's set to an incorrect value?

When is the code thrown exactly? Is it thrown the first time you to send a request with `appOctokit`?

Depending on your use case, you might also be interested in the App SDK:
https://github.com/octokit/app.js/

**Comment by azgorov** [comment]
Thank you @gr2m . It seems that it was some strange case. I have recreated app with new private key and it seems to work. You can just delete this issue.

Kalin

**Comment by gr2m** [comment]
Thanks Kalin. Maybe there is some encoding error in the code that only occurs if the keys has specific characters. If the problem occurs again please let us know
