### ISSUE TITLE
Improve error message when `privateKey` is not a single line String

### ISSUE THREAD

**Issue by oscard0m** [octokit/auth-app.js#311]
**Context:** [40:09 in Reusing GitHub Apps and Actions with Gregor Martynus](https://www.twitch.tv/videos/1102860651?t=40m09s)

---

I can take it once we agree on how to tackle this :)

**Comment by gr2m** [comment]
Thanks for filing the issue! I think the right place to add better errors would be here:

https://github.com/octokit/auth-app.js/blob/348568d43bbd1a0cd1f8383b3e3fd309ac8f91b4/src/get-app-authentication.ts#L10-L14

We could wrap the code into a `try/catch` and in case of an error check if `privateKey` is only the first line of the private key, which is 

```
-----BEGIN RSA PRIVATE KEY-----
```

And if it is, throw an error with a more helpful error message?
