### ISSUE TITLE
Bug: Error trying to get organization's installed apps

### ISSUE THREAD

**Issue by MaxPCider** [octokit/auth-app.js#374]
When trying to list an organization's installed apps (`GET /orgs/{org}/installations`) GitHub returns "Bad Credentials" error.

`const client = new Octokit({
      authStrategy: createAppAuth,
      auth: {
        appId,
        privateKey,
        installationId,
      },
    });
     await client.request('GET /orgs/{org}/installations', { org: 'someOrg' }); // throws error`

The plugin tries to access the API authecnticated as the app while this route requires installation auth.
the issue seems to be in the `requires-app-auth` regex which, which should return false.

`const url= '/orgs/some-org/installations';
requiresAppAuth(url); // returns true but should return false`

**Comment by timrogers** [comment]
@MaxPCider Thanks for reporting this issue! Have you validated that you're able to hit the API successfully with an authentication token? If so, would you be open to making a PR to fix `requiresAppAuth`?

**Comment by gr2m** [comment]
`requiresAppAuth("GET /orgs/{org}/installations")` returns false to me. Are you sure you are not using the `GET /orgs/{org}/installation` route instead?

**Comment by gr2m** [comment]
It's possible that we added `[^/]*` to match GET requests with query parameters. We should add a test which sends a GET request with query parameters, we don't seem to test it right now. Once we have the test, when removing `[^/]*` the test should fail, so we should replace it with something that matches a `?` explicitly to make the failing test pass again. 

We should also add a test for `GET /orgs/{org}/installations` and make sure it fails with the current code.
