### ISSUE TITLE
[FEAT]: When will the conversion to ESM happen?

### ISSUE THREAD

**Issue by ollie-iterators** [octokit/auth-app.js#434]
### Describe the need

I have noticed that there are lots of Pull Requests, like https://github.com/octokit/auth-app.js/pull/425 that are said to be blocked because of the need to use ESM in the modules. I also notice that ESM-ifying the repositories is the next step to be done in the plan to separate types from code and make the types composable/extendable (Shown in https://github.com/octokit/octokit.js/issues/2127)

### SDK Version

Octokit.rb v6.0.0

### API Version

ex v1.1.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Progress is happening, slowly.
We aren't just simply migrating to ESM, some modules are being rewritten, split up

See https://github.com/octokit/octokit-next.js
