### ISSUE TITLE
Getting the correct `installation_id` to use

### ISSUE THREAD

**Issue by nukeop** [octokit/auth-app.js#437]
Hi, thanks for this great and easy to use SDK. It's a joy to use.

I'm writing a Github app that users can install for their entire account or for particular repositories.  Then after an issue is created in a repository covered by my app, I want to react to this event. At this point, Github calls my app's endpoint, and passes an installation id I can use to e.g. reply to the newly created issue.

Now I want to decouple the reaction to the event from registering it. For example, when an issue is created, my app will start an asynchronous job, and later when it finishes, it will reply to the created issue. The problem is that the job scheduler and executor are different services, and the executor doesn't have access to the original event passed by Github. 

So when I want to reply to an issue now, I can't authenticate, because I don't have the `installation_id` needed to do so. Should I store the id passed to github in the original event, so that other services can use it? Or is it possible to retrieve an `installation_id`, given a username/repository and my apps client id?

Similar (but doesn't solve my problem): https://github.com/octokit/auth-app.js/issues/233

**Comment by kfcampbell** [comment]
> Should I store the id passed to github in the original event, so that other services can use it? Or is it possible to retrieve an installation_id, given a username/repository and my apps client id?

I'm not aware of a public API where this is possible. I'm looking in [GitHub Apps docs](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28) here; [Installations docs](https://docs.github.com/en/rest/apps/installations?apiVersion=2022-11-28#about-github-app-installations) has a [Get an app](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-app) endpoint that looks promising but ultimately doesn't give any installation information. 

You can [Get an installation](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-an-installation-for-the-authenticated-app) after [listing installations](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#list-installations-for-the-authenticated-app) but only if you're already authenticated as the app. In this scenario, would that work for you?

**Comment by nukeop** [comment]
Hm, I don't think so, I managed to make it work by storing an installation id with each job's data, and using that to authenticate - not sure how idiomatic that is.

**Comment by kfcampbell** [comment]
I unfortunately don't have a great answer for you there. The installation_id isn't secret, which makes me think it's probably okay. It's available in the URL when viewing an installation in the UI, so I think it's a public identifier.

**Comment by nukeop** [comment]
Alright, I guess this will work for me. Thanks for your help.

**Comment by gr2m** [comment]
> Should I store the id passed to github in the original event, so that other services can use it?

Yes

> Or is it possible to retrieve an `installation_id`, given a username/repository and my apps client id?

As long as you are authenticated as the app (ID + private key), you can retrieve the installation using this endpoint

[`GET /repos/{owner}/{repo}/installation`](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-a-repository-installation-for-the-authenticated-app)
