### ISSUE TITLE
[DOCS]: Node version requirements

### ISSUE THREAD

**Issue by kingledion** [octokit/auth-app.js#503]
### Describe the need

I would like it be better documented which versions of this library match up with which NodeJS versions. 

I'm attempting to use this library with a GitHub Action written in Node, where my only option is node16. But it looks like node 16 support was deprecated with v5.

Is this library even intended to be used with a [Javascript Action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action)? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingledion** [comment]
I had a variety of problems that appear to be completely solved by pinning version to 4.0.13.

Are there any plans to continue the 4.x version series to keep this package compatible with Javascript GitHub Actions?

**Comment by gr2m** [comment]
I hope that github actions will support `node18` as a runner soon. For the time being, you can use version `4.x`. It's a maintenance release that we can accept pull requests for and will roll back critical security fixes too, but it's not actively maintained in terms of adding new features or updating dependencies

**Comment by wolfy1339** [comment]
GitHub now has `node20` for runners
