### ISSUE TITLE
Best Practise Proxy Support 😀👏🏼

### ISSUE THREAD

**Issue by NickLiffen** [octokit/auth-app.js#54]
Hey 👋🏻,

I have a question, we are looking to use this module alongside the [@octokit/graphql.js](https://github.com/octokit/graphql.js/). 

We work behind a corporate proxy, so we need to be able to pass a proxy to any egress request from within our network. 

I see that both this and the `@octokit/graphql.js` modules use the [@octokit/request.js)](https://github.com/octokit/request.js) module to make its requests to the GitHub API.

By taking a look at your [code](https://github.com/octokit/request.js/blob/master/src/fetch-wrapper.ts#L2), you seem to be using [node-fetch](https://github.com/node-fetch/node-fetch) for actually making the HTTP Requests behind the scenes. 

Taking a look at [node-fetch](https://github.com/node-fetch/node-fetch/commit/e5ff203ef41186954b5eea1ddc3b3b0c31c23593) it does support passing in an agent. When taking a look at your request library, there doesn't seem to be any options, which I would have expected to see [here](https://github.com/octokit/request.js/blob/master/src/fetch-wrapper.ts#L25)? (maybe?)

We would love to be able to pass in a `httpsAgent` somewhere? 

```
const { createAppAuth } = require("@octokit/auth-app");
const httpAgent = new http.Agent({ keepAlive: true });
const httpsAgent = new https.Agent({ keepAlive: true });

const auth = createAppAuth({
  id: 1,
  privateKey: "-----BEGIN PRIVATE KEY-----\n...",
  installationId: 123,
  clientId: "1234567890abcdef1234",
  clientSecret: "1234567890abcdef12341234567890abcdef1234"
});

const installationAuthentication = await auth({ 
  type: "installation" ,
  agent: url => url.protocol === 'https:' ? httpsAgent : httpAgent
});

const graphqlWithAuth = graphql.defaults({
  request: {
    hook: auth.hook
    agent: url => url.protocol === 'https:' ? httpsAgent : httpAgent
  }
});
```

Something like that? It would be great if we could do this in a single place when looking through the `octokit` modules, it would be great to have a single experience across the `@octokit` ecosystem 🤔?

Just wanted to put it here and get some of your thoughts on best practice 👍 

Thanks for all your help.

**Comment by gr2m** [comment]
What I would suggest you do is to use https://github.com/octokit/core.js where you can pass `{ request: { agent } }` to setup a proxy. The full code would look like this

```js
const { Octokit } = require('@octokit/core')
const { createAppAuth } = require("@octokit/auth-app");
const httpsAgent = new https.Agent({ keepAlive: true });

const MyEnterpriseOctokit = Octokit.defaults({
  authStrategy: createAppAuth,
  baseUrl: YOUR_ENTERPRISE_BASE_URL,
  request: { agent: httpsAgent }
})

const octokit = new Octokit({
  auth: {
    id: 1,
    privateKey: "-----BEGIN PRIVATE KEY-----\n...",
    installationId: 123,
    clientId: "1234567890abcdef1234",
    clientSecret: "1234567890abcdef12341234567890abcdef1234"
  }
})

octokit.graphql(query, variables)
```

If you don't want to use `@octokit/core`, you can create a custom `@octokit/request` instance and pass that to both, `@octokit/graphql` ([see docs](https://github.com/octokit/graphql.js#use-custom-octokitrequest-instance) and `@octokit/auth-app` (via [`request` option](https://github.com/octokit/auth-app.js/#createappauthoptions))

Does either work for you?

**Comment by gr2m** [comment]
let me know if you have further questions
