### ISSUE TITLE
Default flow results in error for missing installationId

### ISSUE THREAD

**Issue by spew** [octokit/auth-app.js#578]
### What happened?

The README.md gives the following code example for authenticating as an app. 

```
const appOctokit = new Octokit({
  authStrategy: createAppAuth,
  auth: {
    appId: 1,
    privateKey: "-----BEGIN PRIVATE KEY-----\n...",
    clientId: "1234567890abcdef1234",
    clientSecret: "1234567890abcdef1234567890abcdef12345678",
  },
});

// Send requests as GitHub App
const { slug } = await appOctokit.request("GET /user");
console.log("authenticated as %s", slug);
```

If one tries to use this code (with valid values for the private key, client secret, etc), the following client-side error occurs:

```installationId option is required for installation authentication```

This means the library is unuseable without an app installation. If this is desired and correct behavior, then please adjust the README examples.

### Versions

Octokit 3.1.2
Node v18.17.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
It's `/app`, not `/user`. Try this instead

```js
const { slug } = await appOctokit.request("GET /app");
console.log("authenticated as %s", slug);
```

**Comment by spew** [comment]
Right, but the README says to use `GET /user`.

The implication is that an app could make requests like, "list users" and things like that without having an installation. However, this is impossible.
