### ISSUE TITLE
[BUG]: require("@octokit/auth-app"); Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by gfrid** [octokit/auth-app.js#624]
### What happened?

require("@octokit/auth-app"); cant work with NestJS

### Versions

node: v20.10.0
nest: 10.4.1

### Relevant log output

```shell
const auth_app_1 = require("@octokit/auth-app");
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\GitHub\auth\hello-world\node_modules\@octokit\auth-app\dist-node\index.js from C:\GitHub\auth\hello-world\dist\app.service.js not supported.
Instead change the require of index.js in C:\GitHub\auth\hello-world\dist\app.service.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\GitHub\auth\hello-world\dist\app.service.js:11:20)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This is not a bug. We switched to ESM

**Comment by gr2m** [comment]
You can use the last version supporting CJS which currently is 6.1.1. We can still accept bug fixes and will apply security fixes to `6.x`, but we do recommend to upgrade to ESM, as we won't add more features to 6.x

**Comment by gfrid** [comment]
so apperantly the ESM community does not want to deal with commonjs and Nest community don't want to deal with EMS, they both argue a lot on github community but i came with solution:

tsconfig: 
```
{
  "compilerOptions": {
    "module": "Node16", << --- Using await import() with moduleResolution set to nodenext or node16
    "esModuleInterop": true,
    "target": "ESNext",
    "moduleResolution": "node16", <--- Using await import() with moduleResolution set to nodenext or node16
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules"]
}

import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  async getHello(): Promise<string> {
    const { createAppAuth } = await import('@octokit/auth-app');
    const { Octokit } = await import('@octokit/rest');```

**Comment by gfrid** [comment]
> You can use the last version supporting CJS which currently is 6.1.1. We can still accept bug fixes and will apply security fixes to `6.x`, but we do recommend to upgrade to ESM, as we won't add more features to 6.x

Nest dont want to support ESM, people in their community leaving :) LOL

**Comment by gr2m** [comment]
I heard [Fastify](https://fastify.dev/) is great 😉
