### ISSUE TITLE
[BUG]:  Update 6.1.0 -> 6.1.1 results in runtime error in AWS

### ISSUE THREAD

**Issue by npalm** [octokit/auth-app.js#634]
### What happened?

Upgrading from 6.1.0 to 6.1.1 results in a runtime (type) error `response.json(...).catch is not a function` The cause seems to be one of the transivive dependencies updated in the patch release as well.

### Versions

6.1.1

### Relevant log output

Runtime we catch the following generic error. Which seems related to an underlying type issue:

```
 HttpError: response.json(...).catch is not a function
```

See here the PR containing the version update and related packages bumped in the lock file.: https://github.com/philips-labs/terraform-aws-github-runner/pull/4042

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This seems more like an issue with AWS then our code. It seems some platforms are using a non-standard fetch implementation.

All of our tests pass, and there haven't been any issues filed with standard nodejs environments...

All of the dependencies use `@octokit/request` to make requests...

Are you able to post a complete error stack trace?

**Comment by wolfy1339** [comment]
Can you also dedupe your lock file? You have multiple versions of `@octokit/request` at the same time

**Comment by wolfy1339** [comment]
I assume that the error message refers to the following feature that was added https://github.com/octokit/request.js/pull/648

**Comment by wolfy1339** [comment]
Can you see if using `node-fetch` solves the issue for you?

Instructions on patching out fetch can be found here: https://github.com/node-fetch/node-fetch?tab=readme-ov-file#providing-global-access

Don't forget to use the [--no-experimental-fetch](https://nodejs.org/api/cli.html#--no-experimental-fetch) flag

**Comment by npalm** [comment]
Thanks for the pointers. We indeed override some time back the default fetch implementation. Due to the fact tracing in Node 18 was not working with AWS powertools. Resulting in that we could not trace calls to GitHub. This problem is now resolved in the AWS XRay sdk, and will be solved when lambda (AWS) moves to Node 22 (nov 24).

Thanks for the quick feedback!
