### ISSUE TITLE
Throw helpful error  is installationId is unset

### ISSUE THREAD

**Issue by Gopid** [octokit/auth-app.js#64]
I'm following [this](https://github.com/octokit/auth-app.js#createappauthoptions) basic example and I'm getting the JWT back fine but I'm getting a 404 for the installation access token. Tried hitting the api directly too, getting a 404 from there as well.

- using the right private key, checked the fingerprint
- tried making the app / repo public
- the app id is definitely correct
- checked the signature of the generated JWT

but still calling this endpoint responds with 404

curl -i -X POST \
-H "Authorization: Bearer YOUR_JWT" \
-H "Accept: application/vnd.github.machine-man-preview+json" \
https://api.github.com/app/installations/:installation_id/access_tokens

Can't work out what I'm missing here would appreciate any help

**Comment by Gopid** [comment]
So now I can get an access token without this package (realised that app id is different from installation id 🤦) but I'm still not sure why `auth({ type: 'installation' })` is not returning an access token

**Comment by Gopid** [comment]
Ok, got it, need to provide installationId either for createAppAuth or auth, might be worth throwing an error in this case? 'Need to provide an installation id either to createAppAuth or auth' or something

**Comment by gr2m** [comment]
> might be worth throwing an error in this case

Absolutely! I thought we did that already, I'll look into it. Sorry for that! Glad you got it working
