### ISSUE TITLE
[BUG]: 6.1.3 introduced breaking change regarding required Node.js version

### ISSUE THREAD

**Issue by pkerschbaum** [octokit/auth-app.js#653]
### What happened?

In 6.1.3, `lru-cache` was switched to `@wolfy1339/lru-cache@^11.0.2-patch.1`.  
That has stricter `package.json#engines.node` requirements (>=18.20), breaking projects which have Node.js ^18 (previously supported version) and do strict engines checking.

See `package.json#engines.node` of https://www.npmjs.com/package/@wolfy1339/lru-cache/v/11.0.2-patch.1?activeTab=code.

### Versions

6.1.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
The `lru-cache` package was removed

**Comment by wolfy1339** [comment]
Fixed by https://github.com/octokit/auth-app.js/pull/654
